openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Survey API"
  description: "설문조사 API"
servers:
  - description: SurveyAPI
    url: http://localhost:3000/
paths:
  /admin:
    post:
      summary: 관리자계정로그인 API
      description: 세부내용
      parameters:
        - in: query
          name: password
          description: 관리자계정 비밀번호 입력
          require: true
          schema:
            type: string
      responses:
        "200":
          description: 정상
          content: 
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  token:
                    type: string
        "401":
          description: 비밀번호 오류
          content: 
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
  /survey:
    post:
      summary: 설문지 생성 API
      parameters:
        - name: title
          in: query
          description: 설문지 내용 전송
          require: true
          schema:
            type: object
            properties:
              kinds:
                type: integer
                example: 0
              title:
                type: string
                example: 설문지의 제목
              required:
                type: boolean
                example: true    
      responses:
        "200":
          description: 정상
          content: 
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                example: success
        "400":
          description: sequelize에러
          content: 
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: error